name: Guy King Homepage Wiki
version: 3.0.3
url: https://guyrking.com
future: true

author:
  name: Guy King
  email: guy@zorncapital.com

baseurl: /blog

builds:
  - Any
  - Static
  - Jekyll

plans:
  - Free
  - Basic
  - Pro

hostings:
  - Any
  - CloudCannon

collections:
  system_architecture:
    title: System Architecture
    permalink: /system-architecture/:title/
    active_prefix: system-architecture
    output: true
    order: 1
  workflow:
    title: Workflow
    permalink: /workflow/:title/
    active_prefix: workflow
    output: true
    order: 2
  common_tasks:
    title: Common Tasks
    permalink: /common-tasks/:title/
    active_prefix: common-tasks
    output: true
    order: 3

defaults:
- scope:
    path: ""
  values:
    layout: docs
